services:
  db:
    image: docker.1ms.run/postgres:16
    container_name: daicol-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: daicol
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: daicol-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/daicol
      JWT_KEY: your-secret-jwt-key
      INIT_ADMIN_PHONE: 13012011000
      VOLCENGINE_API_KEY: 
      PUBLIC_HOST: https://localhost:3000/
      PUBLIC_BEIAN_NUMBER: 苏@BEIAN_NUMBER


# volumes:
#   db_data: