import { AppCategories, AppStatus } from '$lib/share/app.ts';
import { sql } from 'drizzle-orm';

const appSeeds = [
	{
		routeId: 10001,
		name: '手办生成',
		category: AppCategories.CreativeDesign,
		description: '用任意图片生成真实手办',
		seoKeywords: [
			'doubao-seedream',
			'Nano Banana',
			'手办生成',
			'AI手办',
			'创意设计',
			'3D模型生成',
			'个性化手办',
			'虚拟模型',
			'动漫周边设计',
			'模型定制',
			'AI建模',
			'3D打印'
		],
		seoDescription:
			'Nano Banana 手办生成与创意设计应用！利用顶尖AI技术，将您的想法一键转化为高精度3D手办模型。实现个性化手办定制、动漫周边设计和虚拟模型创作。您的专属AI建模工作室，让创意直达3D打印！',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original.webp',
		handledImg: '/imgs/10001/handled.webp',
		icon: '/imgs/10001/icon.webp',
		barImg: '/imgs/10001/banner.webp',
		rate: sql`'5.0'::numeric`,
		useCount: 230,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['手办'],
		prompt:
			'Create a 1/7 scale commercialized figurine of the characters in the picture, in a realistic style, in a real environment. The figurine is placed on a computer desk. The figurine has a round transparent acrylic base, with no text on the base. The content on the computer screen is a 3D modeling process of this figurine. Next to the computer screen is a toy packaging box, designed in a style reminisc'
	},
	{
		routeId: 10002,
		name: '日式四宫格漫画',
		category: AppCategories.CreativeDesign,
		description: '使用人物图片生成日式四宫格漫画',
		seoKeywords: [
			'豆包AI',
			'四宫格漫画',
			'日式漫画',
			'AI漫画',
			'漫画生成器',
			'创意设计',
			'漫画分镜',
			'故事创作',
			'漫画应用',
			'动漫风格',
			'视觉叙事'
		],
		seoDescription:
			'日式四宫格漫画 & 创意设计 神器！一键将文字想法转化为日系动漫风四格漫画。快速生成漫画分镜，轻松进行故事创作和视觉叙事。你的专属AI漫画生成器，让创意无限放大！',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original.webp',
		handledImg: '/imgs/10002/handled.webp',
		icon: '/imgs/10002/icon.webp',
		barImg: '/imgs/10002/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 219,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['漫画'],
		prompt:
			'四宫格，将原图主体转换成四宫格漫画分镜布局，日式少年漫画风格（类似 Jump 系笔触），每格呈现不同生动表情（包含惊讶张嘴、傲娇瞪眼、害羞带红晕、兴奋怒吼等神态），搭配漫画特效元素（速度线、日文拟声词 、感叹符号 “!!！” 等），四格中间交汇处有爱心边框嵌套原图主体的完整抠图形象，整体为手绘漫画质感、色彩鲜亮，AI 生成宫格漫画形式。'
	},
	{
		routeId: 10003,
		name: '冷艳写真',
		category: AppCategories.EnhanceImages,
		description: '使用人物图片生成冷艳风格的写真',
		seoKeywords: [
			'豆包AI',
			'冷艳写真',
			'创意设计',
			'AI写真',
			'艺术照生成',
			'赛博朋克',
			'极简主义',
			'风格化人像',
			'AI P图',
			'虚拟模特',
			'摄影应用'
		],
		seoDescription:
			'冷艳写真 & 创意设计 专属应用！一键生成高级感、赛博朋克、极简主义等风格化人像。告别复杂P图，用AI快速打造独一无二的冷艳写真和艺术照。您的虚拟模特和设计灵感库！',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original.webp',
		handledImg: '/imgs/10003/handled.webp',
		icon: '/imgs/10003/icon.webp',
		barImg: '/imgs/10003/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 210,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['美图'],
		prompt:
			'使用参考图片人物的脸;写实风格人像摄影，纯欲风格，乌黑黑长直发女性，厚齐刘海，发丝顺滑自然、光泽感清晰；浅灰色纹理上衣，黑色精致颈饰（黑色蕾丝颈链+黑色小吊坠），姿势冷艳：双臂交叉于身前，姿态优雅冷艳，微微侧身，头微微上扬，眼神微俯视镜头，散发冷艳高傲气场；肤质细腻光滑，五官精致立体；妆容突出：漂亮眼妆，纤长睫毛，高光鼻梁，雾面口红，眼神冷艳神秘，带压迫感；背景由多幅黑白动漫人物插画构成，风格各异，眼神或灵动或冷峻，与主体相互映衬；现实与二次元融合氛围，打破次元壁，奇幻感与真实感共存；柔和光线，高清质感，整体饱和度低，偏冷色调时尚写真氛围，9:16比例，主体写实。'
	},
	{
		routeId: 10004,
		name: '地标建筑',
		category: AppCategories.CreativeDesign,
		description: '用任意图片的主体生成地标建筑',
		seoKeywords: [
			'豆包AI',
			'地标建筑设计',
			'创意设计',
			'建筑概念图',
			'AI建筑生成',
			'城市规划',
			'未来建筑',
			'景观设计',
			'建筑可视化',
			'AI绘图',
			'设计灵感'
		],
		seoDescription:
			'地标建筑 & 创意设计 专属工具！一键生成震撼的未来建筑和城市地标概念图。快速获取建筑设计灵感，轻松实现景观设计和建筑可视化。您的专属AI建筑生成器，激发无限创意，革新城市规划！',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original-snoopy.webp',
		handledImg: '/imgs/10004/handled.webp',
		icon: '/imgs/10004/icon.webp',
		barImg: '/imgs/10004/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 210,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['地标', '建筑'],
		prompt:
			'帮我生成图片：图片中的主体放大成巨大，场景是建筑工地，主体有脚手架环绕，脚手架上有工人在活动.原比例.主体写实'
	},
	{
		routeId: 10005,
		name: '清醒系阳光特写',
		category: AppCategories.EnhanceImages,
		description: '生成人物在阳光下的清醒系阳光特写',
		seoKeywords: [
			'萌萌少女特写',
			'细肌十肤',
			'真实质感',
			'魅惑高冷',
			'清醒系阳光',
			'微仰视',
			'散发飘动',
			'眼神闪光',
			'极蓝噪点',
			'蓝白色通透',
			'脸部细节',
			'AI写真'
		],
		seoDescription:
			'【细肌十肤·魅惑高冷少女特写】 真实质感AI写真，微仰视捕捉少女脸部特写。清醒系阳光背景，散乱发丝随风飘动，眼神闪烁魅惑高冷。画面具备极蓝噪点和蓝白色通透的电影级画质。',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original.webp',
		handledImg: '/imgs/10005/handled.webp',
		icon: '/imgs/10005/icon.webp',
		barImg: '/imgs/10005/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 214,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['美图', '阳光'],
		prompt:
			'帮我生成图片：采用细肌”十肤真实质感的风格，画面中展现了一个不改变原图形象的萌萌少女的脸部特写，通过微仰视的镜头角度进行呈现。人物微微抬并且人物不占太多画面。背景营造出清醒系且阳光的场景氛围，少女有着散乱的头发风飘动的感觉，发型不变，发丝随风飘动，不改变原片发色。她的眼神闪闪发光450其中带着阳光和魅惑的情绪，尽显魅惑高冷的气质。画面着重句勒了少女的面部细节高先处理十分讲究，同时画面虽现出带有影机极蓝噪点的画质，并且有着蓝白色通送效果。原比例'
	},
	{
		routeId: 10006,
		name: 'BJD娃娃',
		category: AppCategories.EnhanceImages,
		description: '生成蓝色湿发BJD娃娃人物',
		seoKeywords: [
			'BJD娃娃少女',
			'妖冶特写',
			'细腻皮肤真实质感',
			'腹黑高冷',
			'俯视角度',
			'暗色系阴郁',
			'湿发粘脸',
			'危险眷恋眼神',
			'极蓝噪点',
			'强烈蓝白色曝光',
			'面部细节刻画',
			'AI艺术肖像'
		],
		seoDescription:
			'【BJD娃娃·腹黑妖冶特写】 采用细腻皮肤真实质感风格，以俯视角度呈现BJD娃娃般妖冶少女的脸部特写。背景暗色阴郁，湿漉长发粘附于脸。少女眼神朦胧，透出危险与眷恋的腹黑高冷气质。画面强调极致面部细节，融合极蓝噪点和强烈蓝白色曝光，营造独特的电影感艺术肖像',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original.webp',
		handledImg: '/imgs/10006/handled.webp',
		icon: '/imgs/10006/icon.webp',
		barImg: '/imgs/10006/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 213,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['BJD娃娃少女', '美图', '阴郁', '蓝色'],
		prompt:
			'使用图片人物的脸，帮我生成图片:采用细腻皮肤真实质感的风格，画面中展现了一个bjd娃娃形象的妖治少少女的脸部特写，通过俯视的镜头角度进行虽现。背景为暗色，营造出暗色系且阴郁的场景氛围，少女有着散乱的湿漉漉的长发， 发丝粘在脸上，不改变原片发色。他的眼神胧，其中带着危险和眷恋的情绪，尽显腹黑高冷的气质。画面着重句勒了少女的面部细节，高先处理十分讲究，同时画面虽现出带有摄影机极蓝噪点的画质，并且有着强烈的蓝白色曝先效果。原比例。'
	},
	{
		routeId: 10007,
		name: '宫崎骏画风',
		category: AppCategories.CreativeDesign,
		description: '将图片转为宫崎骏动画的风格',
		seoKeywords: [
			'宫崎骏画风转换',
			'吉卜力风格滤镜',
			'AI动画风格化',
			'人物转宫崎骏',
			'背景转吉卜力',
			'手部细节动画化',
			'衣着一致性转换',
			'高清二次元手绘'
		],
		seoDescription:
			'一键将您的照片转换为宫崎骏动画画风！AI智能保持人物风格完全一致。体验高质量吉卜力风格滤镜，生成专属高清二次元动画图。',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original.webp',
		handledImg: '/imgs/10007/handled.webp',
		icon: '/imgs/10007/icon.webp',
		barImg: '/imgs/10007/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 203,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['漫画', '动画', '宫崎骏'],
		prompt: '转为宫崎骏动画的画风，人物、手部、背景，衣着保持一致'
	},
	{
		routeId: 10008,
		name: '森林人像写真',
		category: AppCategories.EnhanceImages,
		description: '生成极具艺术感的楚辞山鬼主题人像写真',
		seoKeywords: [
			'楚辞山鬼写真',
			'暗黑森林人像AI',
			'油画质感梦核写真',
			'高级感艺术人像生成',
			'强光影对比AI艺术',
			'UE5电影级质感人像',
			'意识流惊悚美学',
			'AI绘画高清Prompt'
		],
		seoDescription:
			'生成极具艺术感的楚辞山鬼主题人像写真。融合油画质感、梦核美学与惊悚元素，实现强光影对比、微距面部聚焦和UE5电影级质感。满足您对高级、意识流AI艺术的创作需求。',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original.webp',
		handledImg: '/imgs/10008/handled.webp',
		icon: '/imgs/10008/icon.webp',
		barImg: '/imgs/10008/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 199,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['森林', '写真', '艺术', '楚辞山鬼'],
		prompt:
			'参考图片人物的脸。昏暗的森林里，人像写真，全身相，虚实变化，光影交错。楚辞山鬼，长头发，超长耳坠，碎发，超多条细长飞舞的发带，宽松纱衣，露出锁骨肩膀，原始，野性，生命力。线条清晰，明暗对比，超高清，高级感，面部特写，最高画质，朦胧感，微距镜头，面部阴影，面部聚焦，丰满，垂眸，凌乱发丝，高质量，油画质感，细腻肌理，仙气灵气围绕着，油画渲染效果。HDR写实质感，不合逻辑，珠光，反光，暗夜，抽象，意识流，梦核，光线暗、能见度低，有噪点暗角。艺术感强。画面有辉光、耀光、雾感，融合惊悚与梦核元素，梦核美学，数字噪音与失真效果，从错误中寻找创意，对现有系统的颠覆与重塑，强烈的光影对比，仰镜头，强烈的对比色碰撞，惊艳，意识流，随机背景，柔和侧光渲染，写实，失真故障质感暗金色点缀，空间交错、电影镜头、(真实感: 1.5)，柔和的色彩，（鱼眼: 1.1)，全景航拍，微光，宿命感，华丽，曜变，UE5渲染，电影级质感，胶片质感。'
	},
	{
		routeId: 10009,
		name: '老照片修复',
		category: AppCategories.EnhanceImages,
		description: '将您的旧照片转化为充满活力色彩分级的高质量图像',
		seoKeywords: [
			'老照片修复专业',
			'顶级肖像摄影风格',
			'照片质量提升AI',
			'现代色彩分级',
			'专业摄影棚效果',
			'保留人物环境修复',
			'老照片高清重塑',
			'摄影级图像增强'
		],
		seoDescription:
			'AI照片修复，完全保留原场景中人物、服装、姿势和环境。将您的旧照片转化为顶级肖像摄影师使用现代专业设备拍摄的，拥有充满活力色彩分级的高质量图像。',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original-2.webp',
		handledImg: '/imgs/10009/handled.webp',
		icon: '/imgs/10009/icon.webp',
		barImg: '/imgs/10009/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 199,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['修复', '写真', '照片', '复古'],
		prompt:
			'修复这张照片。目标是在完全保留原场景中人物、服装、姿势和环境的前提下，使其看起来仿佛是由顶级肖像摄影师使用现代专业设备和充满活力的色彩分级风格在今天拍摄的。不要更改场景中的任何元素，而是从根本上提升图像捕捉的质量。'
	},
	{
		routeId: 10010,
		name: '古风油画写真',
		category: AppCategories.EnhanceImages,
		description: '极致超古风油画美学',
		seoKeywords: [
			'超古风油画',
			'厚涂水粉技法',
			'丁达尔效应古风',
			'树枝角色仰视',
			'低饱和高对比油画',
			'人物光影层次感',
			'雾胧景深古风',
			'长发服饰发饰保留'
		],
		seoDescription:
			'极致超古风油画美学：使用厚涂水粉技法，展现颜料涂抹质感。捕捉低空仰视角度下丁达尔效应光影，营造雾胧景深。完美保留角色发型服饰细节，突出高氛围感主体。',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original.webp',
		handledImg: '/imgs/10010/handled.webp',
		icon: '/imgs/10010/icon.webp',
		barImg: '/imgs/10010/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 189,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['油画', '写真', '古风'],
		prompt:
			'完整保留角色发型和服饰包括发饰。参考有点油画风格，使用厚度和晕染水粉技法，展现出颜料的涂抹质感，营造超古风主义美学的高氛围感和层次感，低空仰视角度。密密匝匝的树叶和树冠，树叶缝隙中撒下阳光形成丁达尔效应，角色闲适地坐在较粗的一处树枝上，低头，脸上有光影，微微俯身看着镜头，一只手抬起扶着树干，裙摆顺着树枝垂下，裙角随风而去荡起，延伸至画面外，柔顺的长发，精致的头饰，素净的妆容，慵懒，深处，仰式视觉。皮肤苍白，绿意盎然的空间，周围光线营造出雾胧的景深氛围，突出人物主体，弱化边缘背景，近实远虚，雾感光源，颗粒感，丁达尔效应光线，高对比度，低保和。比例9:16  油画风格'
	},
	{
		routeId: 10011,
		name: '大头贴四宫格',
		category: AppCategories.CreativeDesign,
		description: '生成漫画风格大头贴四宫格',
		seoKeywords: [
			'四宫格漫画生成',
			'大头贴风格AI',
			'夸张表情动作漫画',
			'可爱彩色背景自拍',
			'个性化贴纸相机',
			'四格漫画制作',
			'拍大头贴滤镜',
			'Q版人物表情包'
		],
		seoDescription:
			'一键生成搞怪可爱的四宫格大头贴漫画！捕捉夸张表情和动作，搭配彩色不重复背景。制作专属的个性化四格漫画和表情包。',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original.webp',
		handledImg: '/imgs/10011/handled.webp',
		icon: '/imgs/10011/icon.webp',
		barImg: '/imgs/10011/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 189,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['大头贴', '漫画', '四宫格'],
		prompt:
			'生成大头贴四宫格漫画，每张照片中的人物有不同的夸张表情和动作，每一格的背景为不相同拍摄大头贴的彩色可爱环境。'
	},
	{
		routeId: 10012,
		name: '时尚冰箱写真',
		category: AppCategories.EnhanceImages,
		description: '生成忧郁克制时尚摄影',
		seoKeywords: [
			'清冷时尚特写',
			'忧郁克制时尚摄影',
			'报纸吊带设计',
			'三分法构图人像',
			'冰箱冷白光剪影',
			'低胸露脐时尚',
			'侧脸低头特写',
			'鸭舌帽造型摆拍'
		],
		seoDescription:
			'清冷克制的时尚大片。三分法构图特写，报纸吊带搭配鸭舌帽，在冰箱冷白光前形成剪影氛围。完美侧脸，眼神忧郁，营造出高级的清冷时尚感。',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original-asian-girl.webp',
		handledImg: '/imgs/10012/handled.webp',
		icon: '/imgs/10012/icon.webp',
		barImg: '/imgs/10012/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 189,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['忧郁', '摄影', '时尚', '冰箱'],
		prompt:
			'使用参考图片人物的脸。这是一张三分法构图的完美杰作，微微俯拍视角，上半身特写，侧身站立，上身紧贴冰箱，主体侧脸，主体轻微低头，不看镜头，主体的脸型和身材不变，主体穿着报纸做成的紧身时尚吊带，超级短款设计，低胸半球设计，露出肚脐，很凸显身材。戴着一个米白色的鸭舌帽，帽沿微微向下快挡住眼睛，在冰箱前摆拍，背景是一个立式冰箱，环境光暗，冰箱门开着，冰箱中有一些啤酒和饮料。冰箱自然的冷白光很亮，照射主体，形成轻微剪影效果的氛围感，能看清主体的侧脸，眼神有点忧郁。总体体现出清冷感。营造忧郁而克制的时尚氛围。'
	},
	{
		routeId: 10013,
		name: '治愈系动物雪景',
		category: AppCategories.EnhanceImages,
		description: '捕捉动物治愈系雪景',
		seoKeywords: [
			'动物雪景写真',
			'猫咪冬日海边',
			'治愈系动物照',
			'雪球动物头顶',
			'蓝色围巾猫咪',
			'富士滤镜动物',
			'童话雪景猫',
			'惬意动物特写',
			'温暖治愈猫咪'
		],
		seoDescription:
			'捕捉动物冬日海边浪漫！特写猫咪惬意神态，头顶雪球，蓝色围巾随风轻扬。富士滤镜下，雪景如童话般宁静治愈，感受独一份的温暖美好。',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original-cat.webp',
		handledImg: '/imgs/10013/handled.webp',
		icon: '/imgs/10013/icon.webp',
		barImg: '/imgs/10013/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 189,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['雪景', '动物', '治愈'],
		prompt:
			'画面中，将动物主体抠出，视角拉近只露出动物上半身，动物神态惬意又满足，头顶还稳稳顶着一个小雪球，脖子上围着一条蓝色的针织围巾，围巾被风吹起，可爱又治愈。背景是冬日的海边雪景，海面平静，岸边的岩石与地面都覆盖着皑皑白雪，在柔和的光线映照下，整个场景像童话般宁静美好，仿佛猫咪正享受着这独一份的冬日浪漫，让人感受到满满的温暖与治愈。整体叠加一层富士滤镜'
	},
	{
		routeId: 10014,
		name: '玫瑰壁画摄影',
		category: AppCategories.EnhanceImages,
		description: '夏日晴空下的梦幻城堡、镜面地面、玫瑰花构成的巨型壁画',
		seoKeywords: [
			'AI绘画超广角',
			'移除背景保留特征',
			'玫瑰花头发壁画',
			'梦幻城堡镜面',
			'夏日晴天棉花糖云朵',
			'8K写实大师级',
			'人像近景全景融合',
			'大景深场景生成'
		],
		seoDescription:
			'8K写实大师级AI绘画，移除原背景并完美保留人物外貌特征。生成超广角宏大场景：夏日晴空下的梦幻城堡、镜面地面、玫瑰花构成的巨型壁画。捕捉人物近景与壁画全景的震撼融合。',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original-asian-girl.webp',
		handledImg: '/imgs/10014/handled.webp',
		icon: '/imgs/10014/icon.webp',
		barImg: '/imgs/10014/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 189,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['玫瑰', '壁画', '梦幻'],
		prompt:
			'去除图中背景，保留人物所有外貌特征不变。夏日晴天，阳光明媚，棉花糖云朵，梦幻城堡的一面墙壁上画着一个巨大图中人物上半身（人物的头发部分由大量的茂盛的和图中人物一样颜色玫瑰花构成，花朵密集，包裹着人物的头顶。这些花密密麻麻覆盖了整个墙头，茂密的长长的花枝垂落下来，地上掉落很多花瓣，花朵细节逼真，花根在一侧墙角一侧），图中人物看着这巨画，人物呈现近景，同时保留巨画的全景。（人物动作符合人物自然工学）背景是城堡，地面是宽阔的无边巨大的镜面，大景深。超广角，写实风格，8k超清，色彩艳丽，大师级作品。'
	},
	{
		routeId: 10015,
		name: '毛绒玩偶挂件',
		category: AppCategories.CreativeDesign,
		description: '按照人物还原为毛绒玩偶挂件',
		seoKeywords: [
			'毛绒玩偶定制',
			'玩偶挂件制作',
			'图片转毛绒公仔',
			'照片定制挂件',
			'去除背景玩偶',
			'个性化毛绒挂件',
			'定制玩偶礼品',
			'毛绒周边制作'
		],
		seoDescription:
			'将您的照片或图片定制为毛绒玩偶挂件！智能去除背景，只保留主体，打造独一无二的个性化毛绒公仔。送礼自用两相宜！',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original.webp',
		handledImg: '/imgs/10015/handled.webp',
		icon: '/imgs/10015/icon.webp',
		barImg: '/imgs/10015/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 189,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['玩偶', '挂件'],
		prompt: '转换为毛绒玩偶挂件，去除背景'
	},
	{
		routeId: 10016,
		name: '宝丽来照片墙',
		category: AppCategories.CreativeDesign,
		description: '电影平面旅行场景照片墙',
		seoKeywords: [
			'8K电影照片墙',
			'宝丽来旅行照片',
			'法罗群岛圣托里尼',
			'冰岛摩洛哥摄影',
			'哈苏135mm',
			'柯达Vision3 250D',
			'lomography颗粒',
			'AI照片墙生成',
			'超逼真电影感'
		],
		seoDescription:
			'生成超逼真8K电影平面照片墙，包含50张宝丽来旅行场景照片（法罗群岛、圣托里尼等）。采用哈苏、柯达Vision3胶片风格，捕捉温暖触感的光影与日记细节。',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original-asian-girl.webp',
		handledImg: '/imgs/10016/handled.webp',
		icon: '/imgs/10016/icon.webp',
		barImg: '/imgs/10016/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 189,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['旅行', '照片墙'],
		prompt:
			'使用参考图中人物的脸，生成超逼真的8K 电影平面照片墙，包含50张宝丽来照片，照片里展现参考人物在旅行场景中的场景﹣﹣法罗群岛、圣托里尼岛、冰岛、日本、摩洛哥、瑞士阿尔卑斯山、巴厘岛、巴黎、纽约﹣﹣具有独特的灯光、手写标题、日记和欢乐；哈苏135mm、柯达 Vision3 250D、lomography 颗粒、温暖的触觉真实感、充满活力和生机。人物只在照片墙内的宝丽来照片中出现，不显示在照片墙前方'
	},
	{
		routeId: 10017,
		name: '水下时尚写真',
		category: AppCategories.CreativeDesign,
		description: '极致水后时尚人物写真',
		seoKeywords: [
			'水下时尚写真',
			'鱼缸人物特写',
			'小丑鱼互动摄影',
			'清透水感写真',
			'暗调高级感人像',
			'水面折射光纹',
			'棕黑色系时尚',
			'极近距离头部特写',
			'梦幻安静水生摄影'
		],
		seoDescription:
			'极致水后时尚人物写真：极近距离头部特写，脸部水光清透。小丑鱼在鱼缸前景穿梭，手部互动。整体棕黑色系暗调，水面折射出碎光斑点，营造梦幻安静的高级感光影写意大片。',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original.webp',
		handledImg: '/imgs/10017/handled.webp',
		icon: '/imgs/10017/icon.webp',
		barImg: '/imgs/10017/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 210,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['写真', '摄影', '水下'],
		prompt:
			'保持脸部不变，水后时尚人物写真，人物头部特写，极近距离拍摄，人物神态自然松弛，清透水感，微光在面部高光浮动。数尾小丑鱼在鱼缸前景缓缓穿梭，尾鳍透明灵动，人物用手和小鱼互动，一只手贴在玻璃上，水面折射出晃动光纹，碎光斑点在脸庞跳跃，水下漂浮粒子环绕，透明水肌理清晰反光。整体氛围梦幻安静，棕黑色系暗调，高级感浓厚，漂浮失焦、动态模糊与细腻胶片颗粒交错，光影写意杰作。整体就是人物在鱼缸玻璃后，和小鱼互动。'
	},
	{
		routeId: 10018,
		name: '洛丽塔动物摄影',
		category: AppCategories.CreativeDesign,
		description: '洛丽塔动物摄影浪漫古典',
		seoKeywords: [
			'洛丽塔动物摄影',
			'猫咪洛丽塔服装',
			'复古动物写真',
			'粉色蕾丝猫咪',
			'贵族风动物照',
			'优雅猫咪特写',
			'奢华动物造型',
			'中世纪风格动物'
		],
		seoDescription:
			'极致洛丽塔动物摄影，捕捉猫咪身着粉色蕾丝华服的优雅瞬间。搭配复古茶具、花艺与贵族家具，营造浪漫古典的奢华氛围。',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original-cat.webp',
		handledImg: '/imgs/10018/handled.webp',
		icon: '/imgs/10018/icon.webp',
		barImg: '/imgs/10018/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 210,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['动物', '摄影', '洛丽塔'],
		prompt:
			'帮我生成图片：以这张动物的照片生成一张洛丽塔风格的动物特写摄影。猫身穿 粉色的蕾丝服饰  ，搭配同风格帽、造型精致华丽 。周围有粉色花艺、复古茶具、中世纪贵族家具，背景是古典装饰，整体营造出优雅浪漫的复古氛围，保持动物原来的样子。原比例。'
	},
	{
		routeId: 10019,
		name: '秋日动物摄影',
		category: AppCategories.CreativeDesign,
		description: '秋日动物摄影头顶枫叶，围巾环绕',
		seoKeywords: [
			'秋日动物摄影',
			'枫叶动物写真',
			'围巾动物照',
			'阳光毛发光晕',
			'秋景背景替换',
			'抠图主体突出',
			'温顺动物神情',
			'户外碎石路面',
			'橙红色枫叶',
			'光影对比摄影'
		],
		seoDescription:
			'极致秋日动物写真！主体安静待着，头顶枫叶、围巾环绕，毛发镀上暖光，背景替换为洒满橙红色枫叶的碎石路面。捕捉动物好奇温顺神情，呈现阳光下鲜明光影对比与浓郁秋日氛围。',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original-cat.webp',
		handledImg: '/imgs/10019/handled.webp',
		icon: '/imgs/10019/icon.webp',
		barImg: '/imgs/10019/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 200,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['摄影', '秋日', '枫叶', '动物'],
		prompt:
			'将主体抠出，画面里，主体安静地待着，头顶俏皮地顶着一片色泽鲜亮的大枫叶，脖子上还围着一条棕色的围巾。阳光透过周围的绿植洒下来，给主体的毛发镀上了一层暖融融的光晕，它睁着眼睛，神情透着几分好奇与温顺，替换背景，背景是秋日户外的地面场景：地面由带有碎石的灰色路面构成，部分区域有开裂、斑驳的质感，旁边散落着大量色泽鲜亮的橙红色枫叶，叶片形态各异，有的完整、有的微微卷曲，为画面增添了浓郁的秋日氛围。画面的明暗关系由侧上方的阳光主导，呈现出鲜明的光影对比与柔和过渡：主体被阳光直接照射的一侧（尤其是面部、耳朵和围巾的受光面），毛发与织物泛着暖金色的明亮高光，轮廓清晰且富有蓬松的质感；而未被阳光直射的另一侧（如身体的背光面、围巾的褶皱暗部），则形成柔和的阴影，让明暗之间的过渡自然、不生硬。背景中，主体与墙面也因光线产生明暗层次，背阴的墙面与地面则偏暗，突出了主体地位'
	},
	{
		routeId: 10020,
		name: '皇冠王子猫',
		category: AppCategories.CreativeDesign,
		description: '捕捉皇冠王子猫的奢华瞬间',
		seoKeywords: [
			'皇冠王子猫',
			'宫廷风动物摄影',
			'复古油画猫咪',
			'奢华皇家布景',
			'镜面倒影猫',
			'动物艺术照',
			'古典宫殿猫',
			'梦幻光影动物'
		],
		seoDescription:
			'捕捉皇冠王子猫的奢华瞬间！在宫廷风背景中，复古油画质感展现身着王子服饰的猫咪，优雅地对着镜子端详自己，倒影与本体服装完美一致。一张融合古典与梦幻的皇家动物艺术照。',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original-cat.webp',
		handledImg: '/imgs/10020/handled.webp',
		icon: '/imgs/10020/icon.webp',
		barImg: '/imgs/10020/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 200,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['动物', '王子', '宫廷', '宫殿'],
		prompt:
			'在奢华无比的宫廷风背景中，复古的台面上，一只头戴璀璨皇冠、身着王子服饰的小猫优雅地坐着，正对着一面精美的镜子端详自己，镜子中有小猫倒影，倒影的服装和本体一致。周围环绕着华丽至极的皇室布景，光影交错，营造出如梦如幻的氛围，每一处细节都散发着古典油画的质感。'
	},
	{
		routeId: 10021,
		name: '国王宝座猫',
		category: AppCategories.CreativeDesign,
		description: '捕捉国王宝座猫的奢华瞬间',
		seoKeywords: [
			'动物国王宝座图',
			'超广角动物特写',
			'动物皇冠披风',
			'创意动物摄影',
			'宫廷风动物照',
			'猫狗国王',
			'动物肖像摄影',
			'可爱动物艺术照'
		],
		seoDescription:
			'创意动物国王大片来袭！坐拥宝座，头戴皇冠，身披王袍，超广角视角突出动物肉垫，尽显王者风范。一张充满趣味与艺术感的宫廷风动物特写，萌翻全场！',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original-cat.webp',
		handledImg: '/imgs/10021/handled.webp',
		icon: '/imgs/10021/icon.webp',
		barImg: '/imgs/10021/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 199,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['动物', '国王', '宫廷', '宫殿'],
		prompt:
			'帮我生成一张图片，图中的环境背景都去除，只保留动物主体，保持动物不变，以动物脚为主题，让动物坐在国王宝座上，双爪扶在宝座上，头戴皇冠和首饰，上身穿着一件国王披风，双腿交叉二郎腿，采用近大远小的构图和超广角视，从右往上的角度拍摄，突出脚在画面中的主体地位，增强空间感和视觉冲击力，动物不要生成人类的脚和手，不要人的脚丫，使用动物符合动物脚爪的浅浅粉色的爪肉垫，比例3:4。背景是在王宫里。'
	},
	{
		routeId: 10022,
		name: '三宫格电影分镜',
		category: AppCategories.CreativeDesign,
		description: '三宫格海边胶片电影写真',
		seoKeywords: [
			'海边写真三宫格',
			'胶片质感艺术照',
			'傍晚沙滩摄影',
			'富士胶片风格',
			'文艺风人像',
			'过度曝光摄影',
			'冷色调写真',
			'自我探索情绪',
			'白衬衣写真',
			'创意字幕摄影'
		],
		seoDescription:
			'探索一组三宫格海边胶片写真：傍晚沙滩，人物身着白衬衣，捕捉风中凌乱发丝。富士胶片般粗粝冷调，过度曝光与柔和光线，营造文艺、自我探索的独特氛围。',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original-asian-girl.webp',
		handledImg: '/imgs/10022/handled.webp',
		icon: '/imgs/10022/icon.webp',
		barImg: '/imgs/10022/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 199,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['三宫格', '海边', '胶片', '电影'],
		prompt:
			"帮我生成图片，一组三宫格胶片质感艺术感写真图，场景为海边沙滩、天空、傍晚。图中人物和参考图一致，人物和脸不变，衣服为白色衬衣。第一张为近景，上半身背影，风吹起头发，发丝凌乱，添加中英字幕“山的后面是什么？-What's beyond the mountain?-”；第二张为中景，人物手持一束花束，侧身站立于海边，看向手中的花，风吹起头发，发丝凌乱，添加中英字幕“你不用告诉我-You don't have to tell me-”；第三张为大特写，人物脸部位于画面偏左侧，风吹起头发，发丝凌乱，添加中英字幕“我会自己去看-I will go see for myself-”。整体色调清冷，带有富士胶片效果，过度曝光，画面粗粝且色调偏冷，暗部细节保留完整，高光区域呈现自然晕化、均采用柔和漫射光，无明显硬边阴影，营造出文艺且充满自我探索情绪的氛围，三张图合成一个三宫格，字幕位于底部居中，比例2:3。"
	},
	{
		routeId: 10023,
		name: '粉色猫妖少女',
		category: AppCategories.EnhanceImages,
		description: '麻花辫与樱花粉色森系服饰，眼神单纯的猫妖少女特写',
		seoKeywords: [
			'猫妖少女',
			'幻想森系服饰',
			'长发麻花辫',
			'樱花粉色服装',
			'珠光纱藤蔓',
			'AI绘画少女',
			'超高清人物特写',
			'复古层叠细节',
			'神秘微光氛围'
		],
		seoDescription:
			'超高清AI生成：皮肤白皙、眼神单纯的猫妖少女特写。描绘其粗长麻花辫与樱花粉色森系服饰，点缀藤蔓花朵，营造神秘微光、清透色彩的幻想风格视觉盛宴。',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original-asian-girl.webp',
		handledImg: '/imgs/10023/handled.webp',
		icon: '/imgs/10023/icon.webp',
		barImg: '/imgs/10023/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 198,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['猫妖', '粉色', '森系', '写真'],
		prompt:
			'一位皮肤白皙、眼神单纯可爱的长发猫妖少女，编着一条粗长麻花辫垂到脚踝，发丝凌乱，身着樱花粉色短款幻想风格森系服饰搭配层叠长片珠光纱，身上缠绕着细细藤蔓、小小枝叶花朵，白色背景，人物特写，幻想风格，浅景深，光斑，光影对比，神秘、微光氛围，服装繁复细节、复古、层层叠叠风格，超高清、面部高清，清透、色彩饱满有层次'
	},
	{
		routeId: 10024,
		name: '甜美草莓主题动物',
		category: AppCategories.EnhanceImages,
		description: '甜美温馨的草莓主题场景草莓蛋糕和动物',
		seoKeywords: [
			'可爱宠物',
			'草莓主题',
			'甜美风格',
			'宠物摄影',
			'温馨场景',
			'红色蝴蝶结',
			'草莓裙子',
			'毛绒玩具',
			'创意图片',
			'生日祝福',
			'宠物萌照',
			'白色线条元素',
			'卡通宠物',
			'节日礼物'
		],
		seoDescription:
			'发现超萌可爱宠物！头戴红色蝴蝶结，身穿草莓裙，坐在草莓座椅上，营造甜美温馨的草莓主题场景。配有“BABY”草莓蛋糕和“Sweet Strawberry”文字，是您寻找创意宠物萌照或生日祝福图片的理想选择！',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original-cat.webp',
		handledImg: '/imgs/10024/handled.webp',
		icon: '/imgs/10024/icon.webp',
		barImg: '/imgs/10024/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 198,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['动物', '草莓', '甜美', '宠物'],
		prompt:
			'可爱宠物，头戴红色大蝴蝶结发箍，身穿草莓图案白色小裙子，歪头微笑 wink 张嘴，在红与米色拼接的背景上，坐在一个大型的草莓毛绒座椅上，抱着一个草莓毛绒玩具，周围有草莓蛋糕毛绒玩具（写有“BABY”）、草莓毛绒玩具，还有文字“!wish you happy everyay!”“Sweet Strawberry”，白色线条元素，甜美草莓主题，温馨场景'
	},
	{
		routeId: 10025,
		name: '日杂复古杂志',
		category: AppCategories.CreativeDesign,
		description: '极致日杂复古杂志风海报设计',
		seoKeywords: [
			'日杂复古海报',
			'胶片颗粒感海报',
			'莫兰迪深蓝色海报',
			'LUCAS杂志标题',
			'猫咪耳机复古风',
			'高级复古海报设计',
			'强制透视海报',
			'橙红撞色设计'
		],
		seoDescription:
			'极致日杂复古杂志风海报设计：莫兰迪深蓝色背景搭配橙红巨大“LUCAS”标题，营造胶片颗粒感的高级复古氛围。主体为戴耳机猫咪，运用强制透视，强调“Seize The moment”！',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original-cat.webp',
		handledImg: '/imgs/10025/handled.webp',
		icon: '/imgs/10025/icon.webp',
		barImg: '/imgs/10025/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 198,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['动物', '日式', '杂志', '宠物', '复古'],
		prompt:
			'日杂复古杂志风海报，复古胶片颗粒感，主色调为莫兰迪深蓝色背景，搭配橙红巨大杂志标题字“LUCAS”，底部下方有小字“Seize The moment”，主体为只露出上半身的猫咪，向右半侧着脸，带着有线耳机听歌，头部上方留出三分之一空间，优雅，高级，复古，强制透视'
	},
	{
		routeId: 10026,
		name: '宠物证件照九宫格',
		category: AppCategories.CreativeDesign,
		description: '极致日杂复古杂志风海报设计',
		seoKeywords: [
			'动物证件照九宫格',
			'白色背景宠物照',
			'宠物多表情证件照',
			'宠物无边框照片',
			'九宫格证件照制作',
			'宠物表情包证件照',
			'AI宠物照片生成'
		],
		seoDescription:
			'生成白色背景的宠物九宫格证件照！捕捉宠物各种可爱表情，无边界线条设计，完美用于社交分享或制作专属宠物卡片。',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original-cat.webp',
		handledImg: '/imgs/10026/handled.webp',
		icon: '/imgs/10026/icon.webp',
		barImg: '/imgs/10026/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 198,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['动物', '证件照', '九宫格', '宠物'],
		prompt: '生成白色背景的，九宫格，宠物证件照，各种表情，不要有边界线条'
	},
	{
		routeId: 10027,
		name: '宠物麦当劳主题照',
		category: AppCategories.CreativeDesign,
		description: '为您的爱宠定制专属麦当劳主题写真',
		seoKeywords: [
			'宠物麦当劳主题照',
			'麦当劳宠物摄影',
			'宠物定制场景',
			'可爱宠物麦当劳',
			'宠物公仔合影',
			'麦当劳主题背景',
			'宠物创意写真',
			'萌宠麦当劳帽子'
		],
		seoDescription:
			'为您的爱宠定制专属麦当劳主题写真！宠物置身于麦当劳背景，搭配系列贴纸、公仔，戴上麦当劳帽子，在毛绒窝中可爱看向镜头。打造萌趣十足的宠物创意摄影！',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original-cat.webp',
		handledImg: '/imgs/10027/handled.webp',
		icon: '/imgs/10027/icon.webp',
		barImg: '/imgs/10027/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 198,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['动物', '摄影', '麦当劳', '宠物'],
		prompt:
			'帮我把背景改成麦当劳背景 墙上贴着一些麦当劳系列贴纸或者海报 地毯要麦当劳系列配色 旁边放着麦当劳系列公仔 宠物头上带麦当劳系列帽子做出可爱的表情看着镜头身上衣服可以改变 表情可爱，宠物窝变成麦当劳系列毛绒样子'
	},
	{
		routeId: 10028,
		name: '国风清宫旗袍动物',
		category: AppCategories.CreativeDesign,
		description: '国风仿清宫格旗袍写真',
		seoKeywords: [
			'仿清宫格旗袍',
			'绒毛旗袍',
			'钿子头饰',
			'长命锁金项圈',
			'故宫宫墙',
			'紫禁城一游',
			'海棠花光影',
			'温馨国风贴纸',
			'角色扮演写真'
		],
		seoDescription:
			'国风仿清宫格旗袍写真：身穿柔和粉色绒毛旗袍，头戴钿子头饰，在故宫朱红宫墙下端庄留影。画面包含长命锁、海棠花光影及“紫禁城一游”印章贴纸，色调温馨，光影效果突出。',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original-cat.webp',
		handledImg: '/imgs/10028/handled.webp',
		icon: '/imgs/10028/icon.webp',
		barImg: '/imgs/10028/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 198,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['动物', '摄影', '旗袍', '宠物', '清宫'],
		prompt:
			'服饰与配饰：身穿一件仿清宫格的柔和粉色锦缎小旗袍，衣襟和袖口镶着柔软的白色绒毛边。头戴一顶毛茸茸的“钿子”头饰，上面精致点缀着珍珠和小流苏。脖子上挂着一个长命锁金项圈。表情与动作：表情端庄又难掩好奇，微微歪着头，一只前爪轻轻搭在故宫鲜艳红色的宫墙上，仿佛在聆听历史的声音。场景描述：在故宫长长的朱红色宫墙下，脚下是斑驳的石板路。墙边有几棵探出枝头的海棠花（或银杏），背景是金色的琉璃瓦屋顶和蓝天。阳光洒下，在墙面上形成光影。贴纸与文字：画面角落有“紫禁城一游”的印章式文字，周围漂浮着小小的云纹、宫灯和飘落的海棠花瓣贴纸，整体色调温馨，光影效果突出。'
	},
	{
		routeId: 10029,
		name: '韩式时尚精致写真',
		category: AppCategories.EnhanceImages,
		description: '高清细腻的年轻女性肖像棕色长卷发与精致妆容',
		seoKeywords: [
			'高清女性肖像',
			'棕色长卷发',
			'精致妆容',
			'钻石耳环项链',
			'白色露肩毛衣',
			'柔和光线',
			'优雅氛围',
			'细腻画质',
			'年轻女性时尚照'
		],
		seoDescription:
			'高清细腻的年轻女性肖像，展现棕色长卷发与精致妆容。她佩戴闪亮钻石首饰，身着白色露肩毛衣，背景简约，光线柔和，营造出优雅精致的视觉氛围。',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original.webp',
		handledImg: '/imgs/10029/handled.webp',
		icon: '/imgs/10029/icon.webp',
		barImg: '/imgs/10029/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 198,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['写真', '韩式', '时尚', '女性'],
		prompt: '将图一人物的脸替换到图二人物的脸，要能够明显看出是图一的人物，其他不变'
	},
	{
		routeId: 10030,
		name: '黏宝耄耋富贵图',
		category: AppCategories.CreativeDesign,
		description: '中国水墨画宠物扑蝴蝶',
		seoKeywords: [
			'中国水墨画',
			'水彩晕染',
			'宠物扑蝴蝶',
			'牡丹花开',
			'溪水潺潺',
			'诗意留白',
			'国画杰作',
			'黏宝耄耋富贵图',
			'书法印章',
			'中式美学',
			'4K高清水墨画'
		],
		seoDescription:
			'欣赏一幅杰作级的中国水墨画，以水彩晕染技法描绘宠物扑蝴蝶的活泼场景。牡丹盛开，小溪潺潺，诗意留白尽显传统美学。作品题有“黏宝耄耋富贵图”隶书书法并印有中国风印章。',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original-cat.webp',
		handledImg: '/imgs/10030/handled.webp',
		icon: '/imgs/10030/icon.webp',
		barImg: '/imgs/10030/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 198,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['耄耋', '动物', '宠物', '水墨画'],
		prompt:
			'帮我生成图片：中国水墨画风格，采用水彩晕染技法，呈现柔和细腻的渐变效果，图中宠物正调皮地用爪子扑着翩翩起舞的蝴蝶，周围牡丹花草丛生，小溪潺潺流淌，盛开的牡丹富贵美丽，宠物拼命扑着，活泼可爱。宠物的毛发以柔和飘逸的墨笔勾勒呈现，牡丹摇曳生姿，蝴蝶灵动美好，通过留白营造诗意构图，尽显中国传统美学，整体氛围宁静和谐，属杰作级别，最高品质，4K（超高清），在这幅水墨画作品中有书法题词隶书字体的“黏宝耄耋富贵图”五个字，印有中国风的印章，形成了一幅完整的水墨画作品'
	},
	{
		routeId: 10031,
		name: '哈利波特宠物',
		category: AppCategories.CreativeDesign,
		description: '哈利波特格兰芬多主题宠物的九宫格魔法世界',
		seoKeywords: [
			'哈利波特宠物',
			'格兰芬多主题',
			'魔法宠物装扮',
			'九宫格排版',
			'宠物魔法造型',
			'霍格沃茨宠物',
			'创意宠物摄影',
			'萌宠魔法世界',
			'格兰芬多红色背景'
		],
		seoDescription:
			'探索哈利波特格兰芬多主题宠物的九宫格魔法世界！看萌宠身着格兰芬多装扮，骑扫帚、戴分院帽、玩魔杖，展现九种创意魔法造型。一张图尽览霍格沃茨萌趣瞬间！',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original-cat.webp',
		handledImg: '/imgs/10031/handled.webp',
		icon: '/imgs/10031/icon.webp',
		barImg: '/imgs/10031/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 198,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['哈利波特', '动物', '宠物', '魔法'],
		prompt:
			'帮我生成图片：这张图片以哈利波特格兰芬多学院的深红色为背景，采用九宫格排版，展示了同一只宠物的九种不同魔法主题装扮状态。第一排左边，宠物戴格兰芬多学院色小发带晃头，仿佛在念咒。第一排中间，宠物骑着扫帚飞。第一排右边，宠物穿格兰芬多学院魔法小斗篷。第二排左边，宠物的右爪子拿着魔法小魔杖，神情略显兴奋。第二排中间是半身照，宠物戴着分院帽眼睛圆溜溜，露出好奇的模样。第二排右边，宠物趴在格兰芬多魔法主题垫子上闭眼睡觉，露出放松的样子。第三排左边，宠物穿红色格兰芬多小毛衣打哈欠。第三排中间，宠物睁眼看魔法地图，呈现好奇的状态。第三排右边，宠物在魔法水晶球的右边坐好，一只爪子搭在水晶球上，保持神秘神态'
	},
	{
		routeId: 10032,
		name: '巧克力曲奇宠物',
		category: AppCategories.CreativeDesign,
		description: '巧克力曲奇花纹毛衣，系着糖霜质感围巾动物',
		seoKeywords: [
			'宠物糖果摩天轮',
			'创意宠物摄影',
			'甜美宠物毛衣',
			'饼干糖果雕塑',
			'温馨宠物画面',
			'Life is Sweet标语',
			'糖霜围巾宠物',
			'巧克力曲奇毛衣',
			'创意美食艺术',
			'宠物治愈系图片'
		],
		seoDescription:
			'瞧这只心满意足的宠物！它身穿巧克力曲奇花纹毛衣，系着糖霜质感围巾，惬意地趴在一个由饼干和糖果制成的摩天轮车厢里。飞溅的牛奶、被咬过的饼干与“Life is Sweet”标语贴纸交织出一幅温馨甜美的画面。这组如同施工雕塑般独具创意的作品，用饼干的暖棕色与糖衣的明亮色彩，完美诠释了生活的甜蜜与美好。',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original-cat.webp',
		handledImg: '/imgs/10032/handled.webp',
		icon: '/imgs/10032/icon.webp',
		barImg: '/imgs/10032/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 198,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['巧克力', '动物', '宠物', '曲奇', '饼干'],
		prompt:
			'宠物穿着一件带有浓郁巧克力曲奇花纹的毛衣，脖子上系着一条糖霜质感的围巾。宠物 趴在一个由各种饼干和糖果组成的摩天轮车厢里，表情满足到极致融化。 饼干的暖棕色与糖衣的高饱和度明亮色彩交织。飞溅的牛奶滴、咬了一口的饼干和“Life is Sweet”的标语贴纸，整体呈现出温馨甜美的氛围，类似施工雕塑般独具创意'
	},
	{
		routeId: 10033,
		name: '路易威登宠物时尚',
		category: AppCategories.CreativeDesign,
		description: '探索路易威登主题奢华宠物时尚大片',
		seoKeywords: [
			'路易威登宠物时尚',
			'LV品牌宠物服装',
			'奢侈品宠物配件',
			'路易威登杂志风摄影',
			'LV老花图案礼盒',
			'设计师宠物服饰',
			'高端宠物生活方式',
			'LV行李箱宠物写真',
			'奢侈品宠物周边',
			'路易威登主题创意摄影'
		],
		seoDescription:
			'探索路易威登主题奢华宠物时尚大片！棕色背景前，萌宠身着LV品牌专属服装，佩戴潮流墨镜，优雅端坐于经典路易威登旅行箱上。画面周围散落着标志性Monogram老花图案礼盒，完美演绎奢侈品与宠物生活的跨界美学。本组作品融合高端时尚杂志摄影风格与奢侈品元素，为追求精致生活的宠物主人提供独具格调的视觉参考，展现路易威登经典设计在宠物时尚领域的非凡魅力。',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original-cat.webp',
		handledImg: '/imgs/10033/handled.webp',
		icon: '/imgs/10033/icon.webp',
		barImg: '/imgs/10033/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 198,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['路易威登', '动物', '宠物', '时尚', '奢华'],
		prompt:
			'将背景改为棕色，整体风格为路易威登主题杂志风，图片中的宠物穿戴路易威登品牌服装，戴着墨镜，坐在路易威登的箱子上，旁边摆放一些带有路易威登老花图案的礼盒'
	},
	{
		routeId: 10034,
		name: '冬日宠物三拼图',
		category: AppCategories.CreativeDesign,
		description: '毛绒耳包和红色针织围巾冬日森林',
		seoKeywords: [
			'冬日猫咪三拼图',
			'宠物治愈系摄影',
			'白色毛绒耳包宠物',
			'红色针织围巾猫咪',
			'雪景森林动物摄影',
			'富士滤镜童话风',
			'猫咪冬日浪漫',
			'积雪宠物近景照',
			'可爱宠物中远景',
			'温暖治愈系图片'
		],
		seoDescription:
			'这张三拼图描绘了一只戴着白色毛绒耳包和红色针织围巾的猫咪，在冬日森林雪景中惬意享受的治愈场景。上方为中远景的雪地松林，中间为猫咪满足的脸部近照，下方为动态的中景镜头。画面中雪花飘落，围巾随风轻扬，猫咪头顶与肩膀覆盖点点积雪，搭配富士滤镜的柔和色调，整体充满童话般的宁静与温暖，传递出冬日的浪漫与治愈力量。',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original-cat.webp',
		handledImg: '/imgs/10034/handled.webp',
		icon: '/imgs/10034/icon.webp',
		barImg: '/imgs/10034/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 198,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['冬日', '动物', '宠物', '雪景', '三拼图'],
		prompt:
			'帮我生成一张三拼图，每个格子中间有一条黑色细条纹，上方格子主体为中远景照，中间格子主体为脸部近景照，下方格子主体中景照，将宠物主体抠出，主体神态惬意又满足，每个格子（主体）都戴着白色毛绒耳包，每个格子（主体）脖子上都围着一条红色的针织围巾，围巾被风吹起，可爱又治愈。背景是冬日的森林，地面都覆盖着皑皑白雪，远处是松树林，天空飘着鹅毛般的大雪，头上肩上围巾上都有一点点白色积雪，在柔和的光线映照下，整个场景像童话般宁静美好，仿佛猫咪正享受着这独一份的冬日浪漫，让人感受到满满的温暖与治愈。整体叠加一层富士滤镜'
	},
	{
		routeId: 10035,
		name: '阳光草地动物肖像',
		category: AppCategories.CreativeDesign,
		description: '毛绒耳包和红色针织围巾冬日森林',
		seoKeywords: [
			'宠物肖像',
			'阳光草地',
			'鲜花环绕',
			'油画背景',
			'宠物项圈',
			'清新自然摄影',
			'宠物艺术照',
			'定制宠物画',
			'高分辨率宠物图片',
			'萌宠',
			'狗肖像',
			'猫肖像',
			'梦幻场景'
		],
		seoDescription:
			'为您呈现一张高清、精美的宠物肖像。画面中，您可爱的宠物保持着真实的样貌，置身于一个阳光明媚、洒满绿意的草地上。它的脖子上戴着由清新花草编制的项圈，周身被黄、绿、白色的鲜艳鲜花环绕。整个画面光影明亮，色调清新自然。独特的创意在于背景中立着一副油画，油画中是以同样草地鲜花为背景的宠物，营造出梦幻而富有艺术感的视觉效果。采用9:16原比例构图，是完美的手机壁纸或艺术收藏。',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original-cat.webp',
		handledImg: '/imgs/10035/handled.webp',
		icon: '/imgs/10035/icon.webp',
		barImg: '/imgs/10035/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 198,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['鲜花', '动物', '宠物', '肖像', '草地'],
		prompt:
			'帮我生成图片：保持现有宠物样貌，脸不变，呈现真实质感的宠物，将宠物置于室外阳光明媚洒满的草地场景中，脖子戴着花草编制的项圈，周围环绕着黄绿白色的鲜艳鲜花，画面清新自然，背后立着一副油画，油画里是以同样草地鲜花为背景的宠物。采用原比例 9:16 构图，光影明亮，色调清新'
	},
	{
		routeId: 10036,
		name: '印象派睡莲池',
		category: AppCategories.CreativeDesign,
		description: '莫奈印象派睡莲池',
		seoKeywords: [
			'莫奈风格转换',
			'印象派油画AI',
			'睡莲池场景生成',
			'主体特征不变',
			'莫奈笔触色彩',
			'睡莲池嬉戏',
			'高清印象派艺术照',
			'柔和光线氛围感'
		],
		seoDescription:
			'将您的主体特征、五官不变地融入莫奈印象派睡莲池！画面采用莫奈式笔触与色彩，光影细腻，充满自然诗意。高清生成睡莲池嬉戏场景，享受浪漫油画氛围感。',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original-cat.webp',
		handledImg: '/imgs/10036/handled.webp',
		icon: '/imgs/10036/icon.webp',
		barImg: '/imgs/10036/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 198,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['印象派', '动物', '宠物', '油画', '睡莲'],
		prompt:
			'保持用户原图主体基本特征、外貌、五官不变。主体在印象派经典场景中，画面采用莫奈式的笔触与色彩，笔触灵动且色彩斑斓，光线柔和富有氛围感。场景是睡莲池里，主体躺在连夜上在嬉戏，睡莲与水纹色彩丰富；整体风格是印象派油画，色彩明快，光影细腻，充满自然诗意与浪漫情调。画面清晰，画质高，高清'
	},
	{
		routeId: 10037,
		name: '梦娜丽莎抱宠',
		category: AppCategories.CreativeDesign,
		description: '欣赏独特的蒙娜丽莎宠物油画！',
		seoKeywords: [
			'蒙娜丽莎宠物油画',
			'复古名画改编',
			'高清油画风格',
			'蒙娜丽莎抱动物',
			'经典艺术混搭',
			'温顺宠物画像',
			'创意名画',
			'艺术再创作'
		],
		seoDescription:
			'欣赏独特的蒙娜丽莎宠物油画！这张高清复古风格创意名画，描绘了蒙娜丽莎怀抱温顺宠物，将经典艺术与现代想象完美结合。',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original-cat.webp',
		handledImg: '/imgs/10037/handled.webp',
		icon: '/imgs/10037/icon.webp',
		barImg: '/imgs/10037/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 198,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['梦娜丽莎', '动物', '宠物', '油画', '复古'],
		prompt:
			'帮我生成图片，梦娜丽莎抱着图中宠物，油画风格，高清，复古风格。宠物温顺的趴在蒙娜丽莎的怀里。'
	},
	{
		routeId: 10038,
		name: '印第安风格猫咪',
		category: AppCategories.CreativeDesign,
		description: '史诗级印第安风格猫咪艺术写真',
		seoKeywords: [
			'印第安猫咪',
			'鹰羽头饰猫',
			'部落图腾战衣',
			'史诗感宠物写真',
			'后现代古风',
			'虚幻5引擎画质',
			'高饱和色调',
			'深咖啡色背景',
			'独特肌理质感',
			'猫咪艺术照'
		],
		seoDescription:
			'史诗级印第安风格猫咪艺术写真：头戴鹰羽头饰，身着部落图腾战衣，于深咖啡色背景中咆哮。融合后现代与浪漫古风，呈现虚幻5引擎般的真实肌理质感与高饱和色调。',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original-cat.webp',
		handledImg: '/imgs/10038/handled.webp',
		icon: '/imgs/10038/icon.webp',
		barImg: '/imgs/10038/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 198,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['印第安', '动物', '宠物', '油画', '写真'],
		prompt:
			'背景换成浓郁复古深咖啡色，头戴印第安鹰羽头饰的猫，身穿饰有部落图腾的印第安风格战衣，宠物坐着，张着嘴咆哮，极具史诗感。合理构图，采用高饱和色调，洒金点缀，融合后现代主义与浪漫古风，呈现独特肌理质感，如真实写真般，似经虚幻5引擎精心打造'
	},
	{
		routeId: 10039,
		name: '宠物画室艺术家',
		category: AppCategories.CreativeDesign,
		description: '可爱宠物身着与水粉画',
		seoKeywords: [
			'宠物画室',
			'水粉画宠物',
			'穿着宠物艺术照',
			'宠物肖像画',
			'画架宠物',
			'室内画室场景',
			'动物艺术家',
			'个性宠物摄影'
		],
		seoDescription:
			'创意宠物艺术照：可爱宠物身着与水粉画一致的服装，坐于画架前，背景是充满艺术氛围的室内画室，彰显个性与品味。',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original-cat.webp',
		handledImg: '/imgs/10039/handled.webp',
		icon: '/imgs/10039/icon.webp',
		barImg: '/imgs/10039/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 198,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['画室', '动物', '宠物', '艺术'],
		prompt:
			'帮我生成图片：仅保留宠物主体，图中宠物坐在一幅与它穿着打扮一致的水粉画前，水粉画画置于画架上，背景为室内画室环境，摆放有其他画作 。比例 3:4。原比例。'
	},
	{
		routeId: 10040,
		name: '宠物哥特风写真',
		category: AppCategories.CreativeDesign,
		description: '超高清宠物哥特风写实艺术照',
		seoKeywords: [
			'宠物哥特风写真',
			'复古暗黑系宠物照',
			'猫咪贝雷帽蕾丝裙',
			'哥特式花卉摄影',
			'神秘复古宠物造型',
			'超高清写实艺术照',
			'暗黑华丽视觉',
			'宠物肖像大师级'
		],
		seoDescription:
			'超高清宠物哥特风写实艺术照：宠物头戴贝雷帽、身着蕾丝裙，置身于鲜花蝴蝶箱中，营造出神秘、复古、华丽的暗黑氛围。色彩对比鲜明，光线立体，突出完美的毛发与服饰细节。',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original-cat.webp',
		handledImg: '/imgs/10040/handled.webp',
		icon: '/imgs/10040/icon.webp',
		barImg: '/imgs/10040/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 198,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['哥特', '动物', '宠物', '复古', '暗黑'],
		prompt:
			'宠物头戴棕色贝雷帽和白色花朵装饰，穿着白色蕾丝娃娃领的黑色波浪样式的裙子，整体造型充满复古哥特风格。坐在装饰有大量鲜花、蝴蝶元素的箱子里，周围有玩偶、各色鲜花和蝴蝶装饰，营造出一种复古、神秘且略带诡异的氛围。摄影风格，搭配色彩斑斓的鲜花，再加上深色背景衬托，色彩对比鲜明，营造出神秘而华丽的视觉效果。宠物处于画面中心位置，周围的鲜花、玩偶等元素丰富了画面层次，构图紧凑且富有故事感，突出神秘复古主题。光线柔和且有明暗对比，突出小猫的面部轮廓、毛发质感以及服装细节，增强画面的立体感和神秘感，营造出浓郁的哥特式氛围。大师写实艺术照，超高清，完美构图'
	},
	{
		routeId: 10041,
		name: '猫咪猫爪特写',
		category: AppCategories.CreativeDesign,
		description: '聚焦猫咪粉色猫爪特写',
		seoKeywords: [
			'猫咪猫爪特写',
			'粉色猫爪图案',
			'But love Pray for me',
			'猫咪手写英文',
			'写实猫咪摄影',
			'暖色柔焦背景',
			'猫咪爪子细节',
			'萌宠图片'
		],
		seoDescription:
			'聚焦猫咪粉色猫爪特写，爪上刻有可爱猫咪图案，并配以“But love Pray for me”手写英文。写实摄影风格，暖色柔焦背景，捕捉萌宠最动人的瞬间。',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original-cat.webp',
		handledImg: '/imgs/10041/handled.webp',
		icon: '/imgs/10041/icon.webp',
		barImg: '/imgs/10041/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 198,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['特写', '动物', '宠物', '猫爪', '猫爪'],
		prompt:
			'帮我生成图片：猫咪向前伸出猫爪，粉色猫爪居于画面中间位置，其中一个猫爪上面刻有猫咪图案，猫爪左侧有白色手写体英文“But love”，右侧有白色手写体英文“Pray for me”，两段英文与图案处于同一水平线且紧密挨着。猫咪面部處化，背景呈暖色调并采用柔焦效果，整体风写实摄影，画面长宽比协调，营造出一种聚）猫爪和图案细节的视觉效果。原比例。'
	},
	{
		routeId: 10042,
		name: '超绝古风清冷感写真',
		category: AppCategories.CreativeDesign,
		description: '超绝古风清冷感写真',
		seoKeywords: [
			'超绝古风写真',
			'清冷感写真',
			'古风大小姐写真',
			'国风艺术摄影',
			'古风氛围感',
			'古风发饰造型',
			'青瓷古画摄影',
			'古风朦胧光感',
			'8K超写实古风',
			'古风特写摄影',
			'古风色彩层次',
			'奇幻国风',
			'古风颗粒肌理',
			'霞帔发饰写真',
			'古风构图艺术'
		],
		seoDescription:
			'超绝古风清冷感写真】以8K超写实画质呈现充满故事感的大小姐氛围，通过朦胧光感与弥散渐变技法，打造兼具颗粒肌理与华丽细节的国风艺术大片。极致渲染流苏霞帔发饰与青瓷古画场景，结合戏剧性明暗对比与三分法构图，塑造具有呼吸感的奇幻国风世界。专注眼部特写与材质透光性，展现超古风主义美学的层次张力与艺术感染力。',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original-asian-girl.webp',
		handledImg: '/imgs/10042/handled.webp',
		icon: '/imgs/10042/icon.webp',
		barImg: '/imgs/10042/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 198,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['特写', '写真', '古风', '清冷感', '复古'],
		prompt:
			'真人写真风格图片风格，色彩丰富，精致的细节。,营造出充满故事感且带着清冷大小姐氛围的画面，打造出画面的颗粒感和肌理感，展现 超古风主义美学 的高级氛围感与层次感。光感朦胧，利用晕染、叠涂、弥散渐变技法，让色彩饱满层次丰富。脸部特写，华丽繁杂精致的造型发饰，流苏，华丽的霞帔发饰，周围有古画青瓷等物，同时有极度精致繁华的花卉插入其中，是一幅极具奇幻色彩的国风画面。最具艺术感的主光源，塑造强烈的立体感、质感与戏剧性明暗对比必须优化构图。突出唯一主体，并遵循三分法、引导线或负空间等经典构图原则，创造呼吸感与叙事张力。将画面细节提升到摄影级/超写实级。极致渲染关键材质的纹理、反光与透光性。根据图像主题，生成一个和谐且富有情绪的色彩分级，营造出独特的氛围。8K分辨率，超真实，具有惊人的细节与艺术感染力，表情要丰富，尤其是眼睛与嘴巴，尽可能甜美，除非环境与造型不允许。拍照视角也可以多样化，不拘一格'
	},
	{
		routeId: 10043,
		name: '复古红唇港风美人',
		category: AppCategories.EnhanceImages,
		description: '沉浸于港风的怀旧时光',
		seoKeywords: [
			'复古红唇港风美人',
			'丝绒旗袍盘发造型',
			'老上海弄堂人像',
			'钨丝灯暖光胶片',
			'柯达胶片颗粒感',
			'35mm人文镜头',
			'怀旧复古色调',
			'港风复古写真',
			'上海滩风情',
			'胶片质感人像'
		],
		seoDescription:
			'沉浸于老上海的怀旧时光。本图展现一位复古红唇的港风美人，身着丝绒旗袍，发型优雅盘起。场景设定在韵味十足的老上海弄堂，在钨丝灯营造的暖光下，采用35mm人文镜头与柯达胶片拍摄，呈现出独特的胶片颗粒感与怀旧色调，在复刻经典风格的同时，完美保留了人物的原生五官特征。',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original-asian-girl.webp',
		handledImg: '/imgs/10043/handled.webp',
		icon: '/imgs/10043/icon.webp',
		barImg: '/imgs/10043/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 198,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['特写', '写真', '老上海', '旗袍', '怀旧'],
		prompt:
			'将画面风格改为：复古红唇港风美人，丝绒旗袍盘发，老上海弄堂，钨丝灯暖光，柯达胶片颗粒感，35mm人文镜头，怀旧色调。保持人物五官特征不变，只改变风格'
	},
	{
		routeId: 10044,
		name: '锦鲤鱼头套宠物',
		category: AppCategories.CreativeDesign,
		description: '锦鲤鱼头套的超萌宠物',
		seoKeywords: ["锦鲤鱼头套宠物", "可爱宠物头像", "羊毛毡风格宠物", "卡哇伊动物设计", "高饱和度萌宠", "毛绒绒宠物插画", "粉色围巾宠物", "简约宠物插图", "32k高清萌宠", "嘟嘟脸宠物", "时尚宠物造型", "丝滑画质动物", "萌态十足设计", "精妙无双宠物艺术", "轻松气氛插画"],
		seoDescription:
			'一只戴着锦鲤鱼头套的超萌宠物，采用羊毛毡风格打造毛绒绒的柔软质感。大大的腮红与粉色围巾衬托出时尚卡哇伊气质，高饱和色彩与简约中景构图相得益彰。丝滑画质下萌宠呈现嘟嘟脸表情，精妙无双的设计完美融合轻松氛围与极致可爱，堪称收藏级治愈系艺术作品。',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original-cat.webp',
		handledImg: '/imgs/10044/handled.webp',
		icon: '/imgs/10044/icon.webp',
		barImg: '/imgs/10044/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 198,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['宠物', '动物', '锦鲤', '头套', '羊毛毡'],
		prompt:
			'图中宠物，头上戴着锦鲤鱼头套，头像设计，大大的腮红，时尚，很可爱，高饱和度，可爱嘟嘟，毛绒绒且柔软，羊毛毡风格，脖子带粉色围巾，非常可爱，卡哇伊，画面简约，高饱和度，轻松气氛，丝滑的画质，中景视角，标准镜头，纯色的背景，简约风格，32k高清图，萌态十足，精妙无双'
	},
	{
		routeId: 10045,
		name: '宠物浴室戏水',
		category: AppCategories.CreativeDesign,
		description: '可爱宠物在充满彩色泡泡的粉色浴缸',
		seoKeywords: ["宠物洗澡", "彩虹泡泡", "戏水时光", "萌宠浴缸", "橡胶小鸭子", "宠物SPA", "泡泡浴", "宠物清洁", "可爱动物", "浴室玩具", "宠物护理", "欢乐洗澡", "萌宠日常", "宠物摄影", "动物可爱瞬间"],
		seoDescription:
			'一只可爱宠物头戴毛茸茸白色浴帽，帽顶坐着黄色橡胶小鸭，正坐在充满彩色泡泡的粉色浴缸中。它双爪捧着一个巨大的彩虹色肥皂泡泡，惊喜地注视着泡泡里折射的七彩光芒。浴缸周围散落着水果香皂、贝壳沐浴瓶，墙上挂着“SPLASH!”防水装饰，整体画面融合蓬松毛巾、光滑橡胶鸭与晶莹泡泡的质感对比，营造出温暖明亮、充满童趣的宠物戏水场景，完美展现宠物洗澡时的快乐时光。',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original-cat.webp',
		handledImg: '/imgs/10045/handled.webp',
		icon: '/imgs/10045/icon.webp',
		barImg: '/imgs/10045/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 198,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['宠物', '动物', '戏水', '浴室', '泡泡'],
		prompt:
			'宠物头戴一个毛茸茸的白色浴帽，浴帽上顶着一个黄色橡胶小鸭子。脖子上围着一条蓬松吸水的白色毛巾。它坐在一个充满彩色泡泡的粉色浴缸里，双爪捧着一个巨大的彩虹色肥皂泡泡，正惊奇地看着泡泡里反射出的七彩光芒，表情是纯粹的快乐和惊奇。浴缸里堆满了彩色泡泡和海洋球。浴缸边缘放着水果形状的香皂、一个贝壳造型的沐浴露瓶。地上铺着柔软的长毛绒地毯。墙上挂着“SPLASH!”的防水字母。整体色彩明亮柔和，以粉色、天蓝和泡泡的彩虹色为主，突出泡泡的轻盈光泽、浴帽和毛巾的蓬松吸水感、橡胶小鸭的光滑质感，营造一个快乐、洁净的戏水时光，光影效果温馨明亮，构图元素丰富和谐'
	},
	{
		routeId: 10046,
		name: '秋日稻田写真',
		category: AppCategories.EnhanceImages,
		description: '一张充满秋日氛围的治愈系稻田写真',
		seoKeywords: [
  "秋日稻田写真",
  "稻田人像摄影",
  "治愈系写真",
  "暖色滤镜照片",
  "中近景人像构图",
  "稻田丰收背景",
  "可爱治愈女孩",
  "人物抠图艺术",
  "秋日丰收氛围",
  "惬意神态人像"
],
		seoDescription:
			'这是一张充满秋日氛围的治愈系稻田写真。画面以中近景构图聚焦于主体脸部，人物头部微仰，双眼惬意眯起，神态满足又可爱。头上点缀着饱满的稻穗，背景替换为金黄的丰收稻田，整体叠加暖色滤镜，营造出温暖、治愈的秋日情怀。完美展现秋收的喜悦与宁静。',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original.webp',
		handledImg: '/imgs/10046/handled.webp',
		icon: '/imgs/10046/icon.webp',
		barImg: '/imgs/10046/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 198,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['秋日', '稻田', '写真', '摄影', '治愈'],
		prompt:
			'帮我生成一张秋日稻田写真，为主体脸部中近景照构图，将主体主体抠出，主体头部微仰起双眼眯着神态惬意又满足，可爱又治愈。头上都顶着一条饱满的稻穗，背景变成稻田丰收的景色，整体叠加一层暖色滤镜'
	},
	{
		routeId: 10047,
		name: '俯拍棉花娃娃互动',
		category: AppCategories.CreativeDesign,
		description: '俯拍视角下的暗调高级感亲子互动',
		seoKeywords: [
  "俯拍视角婴儿",
  "手指触碰特写",
  "暗调温馨亲子照",
  "雨后银杏叶背景",
  "高级感婴儿摄影",
  "黑白球鞋亲子互动",
  "灰色颗粒感路面",
  "婴儿与大人手指",
  "情感互动特写",
  "娃娃抬头镜头"
],
		seoDescription:
			'俯拍视角下的暗调高级感亲子互动。画面中娃娃抬头伸出小手，与镜头外穿着黑白色运动鞋的大人食指轻轻相碰，温馨瞬间被永恒定格。背景是雨后的灰色颗粒感路面，散落的黄色银杏叶与水光交织，营造出充满故事感的氛围。这是一张展现细腻情感与高级摄影美学的创意作品。',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original-doll.webp',
		handledImg: '/imgs/10047/handled.webp',
		icon: '/imgs/10047/icon.webp',
		barImg: '/imgs/10047/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 198,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['俯拍', '娃娃', '玩偶', '互动', '雨后'],
		prompt:
			'帮我生成图片:帮我生成图片：以俯拍视角呈现，保持娃娃原有脸部形象不变；让娃娃抬头，伸出小手用一根食指与镜头外仅露出手和穿着黑白色运动鞋的大人手指相碰；背景替换为雨后带水光的灰色颗粒感路面散落若干黄色银杏叶；整体画面调为暗调高级感氛围突出温馨互动感。”比例1:1。比例 3:4。'
	},
	{
		routeId: 10048,
		name: '巨型手办艺术展览合影',
		category: AppCategories.CreativeDesign,
		description: '艺术展览中与定制巨型手办的互动瞬间',
		seoKeywords: ["艺术展览合影", "巨型手办装置", "萌系艺术风格", "人物与手办对比", "大眼睛手办设计", "定制手办艺术", "展览现场摄影", "比例反差艺术", "高级简约背景", "动漫风格装置", "一致性角色设计", "沉浸式观展体验"],
		seoDescription:
			'本作品捕捉了观众在艺术展览中与定制巨型手办的互动瞬间。装置完美复刻人物的大眼睛萌系特征，保持服饰、发型、配饰的性别与造型一致性。手办以自然站姿耸立于人物斜后方，高达人物1.5倍的比例形成强烈视觉反差，简约的展览空间与柔和光影交织出高级静谧的氛围。通过精准的角色还原与场景构建，展现不崩坏的面部与肢体细节，打造出和谐统一的沉浸式艺术体验。',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original-asian-girl.webp',
		handledImg: '/imgs/10048/handled.webp',
		icon: '/imgs/10048/icon.webp',
		barImg: '/imgs/10048/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 198,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['合影', '巨型手办', '艺术展', '展览', '手办'],
		prompt:
			'原图人物正参加一场艺术展览，并和画面中的装置合影，画面中的装置是巨型手办样式，样式与原图保持一致，其形象具有大眼睛的特征，风格偏向萌系艺术，手办需要与原图主体形象的服饰、配饰、发型、装饰等保持一致，都要保持与主体一致性、性别一致性、人脸一致，且手办要穿上服装。手办以自然站姿立在人物斜侧后方，手办体积大于人物体积，手办高于人物50%左右，营造出强烈的比例反差，背景是简约的观展现场，营造出安静、高级的氛围。整体光影融合、氛围统一，人物脸部、身体、手部不崩坏不错乱。'
	},
	{
		routeId: 10049,
		name: '毛绒玩偶',
		category: AppCategories.CreativeDesign,
		description: 'Jellycat风格毛绒玩具',
		seoKeywords: [
  "Jellycat风格玩偶",
  "柔软毛绒玩具",
  "可爱玩偶设计",
  "独特造型玩偶",
  "安抚玩具",
  "婴儿安全玩偶",
  "创意毛绒公仔",
  "设计师玩具",
  "送礼玩偶推荐",
  "高质感毛绒玩具",
  "童趣玩偶",
  "治愈系公仔"
],
		seoDescription:
			'将经典玩偶转化为充满童趣与治愈力的Jellycat风格毛绒玩具。',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original-cat.webp',
		handledImg: '/imgs/10049/handled.webp',
		icon: '/imgs/10049/icon.webp',
		barImg: '/imgs/10049/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 198,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['Jellycat', '玩偶', '毛绒', '手办', '可爱', '动物', '宠物'],
		prompt:
			'转为jellycat风格的玩偶'
	},
	{
		routeId: 10050,
		name: '水萌写真',
		category: AppCategories.EnhanceImages,
		description: '极具高级感与梦幻氛围的鱼缸人像摄影',
		seoKeywords: [
  "水后时尚写真",
  "鱼缸人像摄影",
  "小丑鱼互动",
  "人物头部特写",
  "清透水感人像",
  "暗调高级感写真",
  "胶片质感摄影",
  "动态模糊光影",
  "梦幻氛围人像",
  "极近距离拍摄",
  "水下摄影创意",
  "光影写意杰作"
],
		seoDescription:
			'这是一组极具高级感与梦幻氛围的【水萌写真】。画面以棕黑色暗调为主，聚焦于人物在鱼缸后的自然松弛神态。极近距离特写下，清透的水感与面部浮动的微光交织，数尾灵动的小丑鱼在前景穿梭，人物手指轻贴玻璃与之互动。水面折射的光纹与跳跃的光斑点缀脸庞，水下粒子环绕，透明的水肌理清晰可见。整体融合了细腻胶片颗粒、动态模糊与漂浮失焦手法，打造出一幅光影写意的视觉杰作。',
		model: 'seedream-4',
		source: '字节跳动',
		originImg: '/imgs/original.webp',
		handledImg: '/imgs/10050/handled.webp',
		icon: '/imgs/10050/icon.webp',
		barImg: '/imgs/10050/banner.webp',
		rate: sql`'4.5'::numeric`,
		useCount: 198,
		points: 1,
		status: AppStatus.Enabled,
		tags: ['摄影', '写真', '水萌', '鱼缸', '水下', '动物', '宠物'],
		prompt:
			'保持脸部不变，水后时尚人物写真，人物头部特写，极近距离拍摄，人物神态自然松弛，清透水感，微光在面部高光浮动。数尾小丑鱼在鱼缸前景缓缓穿梭，尾鳍透明灵动，人物用手和小鱼互动，一只手贴在玻璃上，水面折射出晃动光纹，碎光斑点在脸庞跳跃，水下漂浮粒子环绕，透明水肌理清晰反光。整体氛围梦幻安静，棕黑色系暗调，高级感浓厚，漂浮失焦、动态模糊与细腻胶片颗粒交错，光影写意杰作。整体就是人物在鱼缸玻璃后，和小鱼互动。'
	}
];

export default appSeeds;
