import { db } from "$lib/server/db/index.ts";
import { users } from "$lib/server/db/schema/users.ts";
import logger from "$lib/server/log.ts";
import { UserPermissions } from "$lib/share/user.ts";
import { env } from "$env/dynamic/private";
import { apps } from "$lib/server/db/schema/apps.ts";
import { AppCategories, AppStatus } from "$lib/share/app.ts";
import { sql } from "drizzle-orm";

export async function plantingSeed() {
  logger.info(`plainting database seed`);
  await db.transaction(async (tx) => {
    const count = await tx.$count(users);
    if (count > 0) {
      logger.info("table users already has data, skip plainting");
      return;
    }
    logger.info("table users has not data, plainting");

    const USERNAME = "ADMIN";
    const PHONE_NUMBER = env.INIT_ADMIN_PHONE;
    await tx.insert(users).values({
      userName: USERNAME,
      phoneNumber: PHONE_NUMBER,
      permissions: [UserPermissions.BaseAccess, UserPermissions.AdminAccess],
    });
    logger.info(
      `table users plainted, user_name: ${USERNAME}, phone_number: ${PHONE_NUMBER}`,
    );
  });

  await db.transaction(async (tx) => {
    const count = await tx.$count(apps);
    if (count > 0) {
      logger.info("table apps already has data, skip plainting");
      return;
    }
    logger.info("table apps has not data, plainting");

    for (const item of initApps) {
      await tx.insert(apps).values(item);
    }
  });
}

const initApps = [
  {
    routeId: "10001",
    name: "手办生成",
    category: AppCategories.CreativeDesign,
    keywords: ["手办生成", "大香蕉", "Nano Banana"],
    description: "用任意图片生成逼真手办",
    seoKeywords: [
      "doubao-seedream",
      "Nano Banana",
      "手办生成",
      "AI手办",
      "创意设计",
      "3D模型生成",
      "个性化手办",
      "虚拟模型",
      "动漫周边设计",
      "模型定制",
      "AI建模",
      "3D打印",
    ],
    seoDescription:
      "Nano Banana 手办生成与创意设计应用！利用顶尖AI技术，将您的想法一键转化为高精度3D手办模型。实现个性化手办定制、动漫周边设计和虚拟模型创作。您的专属AI建模工作室，让创意直达3D打印！",
    model: "seedream-4",
    source: "豆包",
    icon: "https://img.daisyui.com/images/profile/demo/yellingcat@192.webp",
    barImg: "",
    rate: sql`'0.0'::numeric`,
    useCount: 0,
    points: 1,
    status: AppStatus.Enabled,
    tags: ["3D", "AI建模", "手办", "定制", "创意"], 
  },
  {
    routeId: "10002",
    name: "AI壁纸大师",
    category: AppCategories.CreativeDesign,
    keywords: ["AI壁纸", "高清", "手机壁纸", "桌面", "图像生成"],
    description: "输入文字描述，生成独一无二的高清手机/桌面壁纸",
    seoKeywords: [
      "AI壁纸",
      "壁纸生成",
      "创意设计",
      "高清图像",
      "个性化壁纸",
      "Midjourney",
      "Dalle3",
    ],
    seoDescription:
      "AI壁纸大师，一键生成超高清、风格多样的手机和桌面壁纸。从赛博朋克到水墨国风，满足你所有的视觉想象。",
    model: "wallpaper-gen-2",
    source: "豆包",
    icon: "https://img.daisyui.com/images/profile/demo/yellingcat@192.webp",
    barImg: "",
    rate: sql`'0.0'::numeric`,
    useCount: 2800,
    points: 1,
    status: AppStatus.Enabled,
    tags: ["壁纸", "高清", "AI绘画", "个性化", "手机"], 
  },
  {
    routeId: "10003",
    name: "品牌Logo生成",
    category: AppCategories.CreativeDesign,
    keywords: ["Logo", "品牌设计", "标志", "矢量图", "AI设计"],
    description: "输入品牌名称和理念，AI生成多种风格的Logo设计方案",
    seoKeywords: [
      "Logo设计",
      "品牌创建",
      "AI设计",
      "矢量Logo",
      "创意设计",
      "商业标志",
    ],
    seoDescription:
      "品牌Logo生成器，为你的初创企业或新项目提供无限设计灵感，快速获得专业级Logo。",
    model: "logocraft-1",
    source: "豆包",
    icon: "https://img.daisyui.com/images/profile/demo/yellingcat@192.webp",
    barImg: "",
    rate: sql`'0.0'::numeric`,
    useCount: 1900,
    points: 1,
    status: AppStatus.Enabled,
    tags: ["Logo", "品牌", "商业", "AI设计", "矢量"], 
  },
  {
    routeId: "10004",
    name: "漫画分镜助手",
    category: AppCategories.CreativeDesign,
    keywords: ["漫画", "分镜", "草稿", "故事板", "二次元"],
    description: "输入场景和角色动作，快速生成漫画草稿分镜图",
    seoKeywords: [
      "漫画制作",
      "故事板",
      "AI绘画",
      "创意设计",
      "动画分镜",
      "草图生成",
    ],
    seoDescription:
      "漫画分镜助手，加速你的创作流程。将文字描述转化为可视化的漫画分镜草图。",
    model: "comic-scene-1",
    source: "豆包",
    icon: "https://img.daisyui.com/images/profile/demo/yellingcat@192.webp",
    barImg: "",
    rate: sql`'0.0'::numeric`,
    useCount: 850,
    points: 1,
    status: AppStatus.Enabled,
    tags: ["漫画", "二次元", "分镜", "故事板", "草稿"], 
  },
  {
    routeId: "10005",
    name: "AI插画师",
    category: AppCategories.CreativeDesign,
    keywords: ["插画", "艺术画", "油画", "水彩", "风格转换"],
    description: "将照片转换为各种艺术风格（如油画、水彩、卡通）的插画",
    seoKeywords: [
      "插画生成",
      "艺术滤镜",
      "风格迁移",
      "AI绘画",
      "创意设计",
      "照片转插画",
    ],
    seoDescription:
      "AI插画师，一秒钟将你的照片变成精美的艺术作品。多种风格任选，轻松创作个人画廊。",
    model: "art-painter-3",
    source: "豆包",
    icon: "https://img.daisyui.com/images/profile/demo/yellingcat@192.webp",
    barImg: "",
    rate: sql`'0.0'::numeric`,
    useCount: 3500,
    points: 1,
    status: AppStatus.Enabled,
    tags: ["插画", "艺术", "风格转换", "油画", "AI"], 
  },
  {
    routeId: "10006",
    name: "室内设计灵感",
    category: AppCategories.CreativeDesign,
    keywords: ["室内设计", "装修", "家居", "风格预览"],
    description: "上传房间照片，AI为你生成不同风格的装修效果图",
    seoKeywords: [
      "室内设计",
      "装修效果图",
      "AI家居",
      "设计灵感",
      "家装预览",
    ],
    seoDescription:
      "室内设计灵感助手，帮助你快速预览多种装修风格，从现代简约到欧式复古，找到你的完美设计。",
    model: "room-style-2",
    source: "豆包",
    icon: "https://img.daisyui.com/images/profile/demo/yellingcat@192.webp",
    barImg: "",
    rate: sql`'0.0'::numeric`,
    useCount: 1200,
    points: 1,
    status: AppStatus.Enabled,
    tags: ["室内设计", "家居", "装修", "效果图", "灵感"], 
  },
  {
    routeId: "10007",
    name: "字体创作大师",
    category: AppCategories.CreativeDesign,
    keywords: ["字体", "书法", "排版", "设计", "艺术字"],
    description: "输入关键词或描述，AI生成独特的艺术字体设计",
    seoKeywords: [
      "字体设计",
      "书法生成",
      "艺术字",
      "创意设计",
      "排版工具",
    ],
    seoDescription:
      "字体创作大师，为你的海报、Logo或标题设计独特的视觉焦点，让文字充满生命力。",
    model: "font-master-1",
    source: "豆包",
    icon: "https://img.daisyui.com/images/profile/demo/yellingcat@192.webp",
    barImg: "",
    rate: sql`'0.0'::numeric`,
    useCount: 650,
    points: 1,
    status: AppStatus.Enabled,
    tags: ["字体", "艺术字", "书法", "设计", "排版"], 
  },
  {
    routeId: "10008",
    name: "无缝纹理生成",
    category: AppCategories.CreativeDesign,
    keywords: ["纹理", "材质", "无缝贴图", "背景"],
    description: "根据描述生成可重复平铺的PBR材质或背景纹理",
    seoKeywords: [
      "纹理贴图",
      "PBR材质",
      "游戏设计",
      "3D建模",
      "创意设计",
    ],
    seoDescription:
      "无缝纹理生成，为游戏开发者和3D设计师提供高质量、可无限平铺的背景和材质纹理。",
    model: "texture-maker-2",
    source: "豆包",
    icon: "https://img.daisyui.com/images/profile/demo/yellingcat@192.webp",
    barImg: "",
    rate: sql`'0.0'::numeric`,
    useCount: 400,
    points: 1,
    status: AppStatus.Enabled,
    tags: ["纹理", "PBR", "3D", "游戏", "无缝"], 
  },
  {
    routeId: "10009",
    name: "情绪可视化",
    category: AppCategories.CreativeDesign,
    keywords: ["情绪", "抽象", "艺术", "心理", "色彩"],
    description: "输入当前情绪和感受，AI将之转化为抽象或具象的视觉艺术作品",
    seoKeywords: [
      "情绪艺术",
      "抽象画",
      "心理疗愈",
      "AI创作",
      "视觉表达",
    ],
    seoDescription:
      "情绪可视化，用色彩和形状表达你的内心世界。一个独特的艺术疗愈和创意表达工具。",
    model: "emotion-art-1",
    source: "豆包",
    icon: "https://img.daisyui.com/images/profile/demo/yellingcat@192.webp",
    barImg: "",
    rate: sql`'0.0'::numeric`,
    useCount: 950,
    points: 1,
    status: AppStatus.Enabled,
    tags: ["情绪", "抽象", "艺术", "心理", "色彩"], 
  },
  {
    routeId: "10010",
    name: "创意广告海报",
    category: AppCategories.CreativeDesign,
    keywords: ["海报", "广告", "宣传图", "创意合成"],
    description: "根据产品和宣传目标，生成极具视觉冲击力的创意广告海报",
    seoKeywords: [
      "海报设计",
      "广告创意",
      "营销设计",
      "AI合成",
      "视觉营销",
    ],
    seoDescription:
      "创意广告海报生成，让你的产品宣传图瞬间抓住眼球。专业级合成效果，引爆社交媒体。",
    model: "poster-creator-3",
    source: "豆包",
    icon: "https://img.daisyui.com/images/profile/demo/yellingcat@192.webp",
    barImg: "",
    rate: sql`'0.0'::numeric`,
    useCount: 1700,
    points: 1,
    status: AppStatus.Enabled,
    tags: ["海报", "广告", "营销", "创意", "合成"], 
  },
  {
    routeId: "10011",
    name: "虚拟形象设计",
    category: AppCategories.CreativeDesign,
    keywords: ["虚拟形象", "头像", "卡通", "IP设计"],
    description: "根据用户描述，生成符合设定的二次元或卡通风格虚拟人物形象",
    seoKeywords: [
      "虚拟人像",
      "AI头像",
      "IP创作",
      "二次元",
      "角色设计",
    ],
    seoDescription:
      "虚拟形象设计，打造你的专属二次元/卡通角色IP。轻松拥有独特的社交媒体头像。",
    model: "avatar-maker-2",
    source: "豆包",
    icon: "https://img.daisyui.com/images/profile/demo/yellingcat@192.webp",
    barImg: "",
    rate: sql`'0.0'::numeric`,
    useCount: 2100,
    points: 1,
    status: AppStatus.Enabled,
    tags: ["虚拟形象", "头像", "二次元", "卡通", "IP"], 
  },
  {
    routeId: "10012",
    name: "艺术字纹理化",
    category: AppCategories.CreativeDesign,
    keywords: ["文字特效", "纹理", "材质", "海报"],
    description: "将普通文字转换为具有金属、岩石、火焰等特殊纹理的艺术字",
    seoKeywords: [
      "文字特效",
      "艺术字",
      "纹理化",
      "创意设计",
      "海报标题",
    ],
    seoDescription:
      "艺术字纹理化，让你的文字设计更具震撼力。一键应用逼真的特殊材质效果。",
    model: "text-texture-1",
    source: "豆包",
    icon: "https://img.daisyui.com/images/profile/demo/yellingcat@192.webp",
    barImg: "",
    rate: sql`'0.0'::numeric`,
    useCount: 700,
    points: 1,
    status: AppStatus.Enabled,
    tags: ["文字特效", "艺术字", "纹理", "材质", "海报"], 
  },
  {
    routeId: "10013",
    name: "建筑概念速绘",
    category: AppCategories.CreativeDesign,
    keywords: ["建筑", "概念图", "草图", "景观"],
    description: "输入建筑类型和环境描述，快速生成高质量的建筑概念设计图",
    seoKeywords: [
      "建筑设计",
      "概念图",
      "景观设计",
      "AI绘图",
      "设计草图",
    ],
    seoDescription:
      "建筑概念速绘，为建筑师和设计师提供快速的初期设计灵感和高质量的概念可视化。",
    model: "archi-sketch-3",
    source: "豆包",
    icon: "https://img.daisyui.com/images/profile/demo/yellingcat@192.webp",
    barImg: "",
    rate: sql`'0.0'::numeric`,
    useCount: 350,
    points: 1,
    status: AppStatus.Enabled,
    tags: ["建筑", "概念设计", "草图", "景观", "AI"], 
  },
  {
    routeId: "10014",
    name: "AI配色方案",
    category: AppCategories.CreativeDesign,
    keywords: ["配色", "色彩", "设计", "网站"],
    description: "根据行业或主题关键词，智能生成专业的网站和品牌配色方案",
    seoKeywords: [
      "配色方案",
      "色彩设计",
      "UI/UX",
      "品牌色",
      "创意设计",
    ],
    seoDescription:
      "AI配色方案，告别选择困难。智能推荐和谐、专业的色彩组合，提升你的设计质感。",
    model: "color-palette-1",
    source: "豆包",
    icon: "https://img.daisyui.com/images/profile/demo/yellingcat@192.webp",
    barImg: "",
    rate: sql`'0.0'::numeric`,
    useCount: 1100,
    points: 1,
    status: AppStatus.Enabled,
    tags: ["配色", "色彩", "设计", "UI", "品牌"], 
  },
  {
    routeId: "10015",
    name: "景深模拟器",
    category: AppCategories.CreativeDesign,
    keywords: ["景深", "虚化", "摄影", "后期"],
    description: "为普通照片添加或调整景深效果，模拟单反相机的大光圈虚化",
    seoKeywords: [
      "景深效果",
      "照片虚化",
      "AI后期",
      "创意摄影",
      "图像处理",
    ],
    seoDescription:
      "景深模拟器，一键让你的手机照片拥有单反级的专业虚化效果，突出主体，美化背景。",
    model: "depth-of-field-1",
    source: "豆包",
    icon: "https://img.daisyui.com/images/profile/demo/yellingcat@192.webp",
    barImg: "",
    rate: sql`'0.0'::numeric`,
    useCount: 900,
    points: 1,
    status: AppStatus.Enabled,
    tags: ["摄影", "后期", "景深", "虚化", "照片"], 
  },
  {
    routeId: "10016",
    name: "几何抽象艺术",
    category: AppCategories.CreativeDesign,
    keywords: ["抽象", "几何", "极简", "艺术"],
    description: "根据颜色和形状的描述，生成极简主义的几何抽象艺术作品",
    seoKeywords: [
      "抽象艺术",
      "几何设计",
      "极简主义",
      "创意生成",
      "AI艺术",
    ],
    seoDescription:
      "几何抽象艺术，用最纯粹的线条和色彩，创作出富有哲思的极简主义艺术品。",
    model: "geometric-art-1",
    source: "豆包",
    icon: "https://img.daisyui.com/images/profile/demo/yellingcat@192.webp",
    barImg: "",
    rate: sql`'0.0'::numeric`,
    useCount: 250,
    points: 1,
    status: AppStatus.Enabled,
    tags: ["抽象", "几何", "极简", "艺术", "AI"], 
  },
  {
    routeId: "10017",
    name: "一键卡通化",
    category: AppCategories.CreativeDesign,
    keywords: ["卡通", "动漫", "滤镜", "二次元"],
    description: "上传人像照片，将其转化为各种风格的二次元卡通形象",
    seoKeywords: [
      "卡通滤镜",
      "二次元化",
      "人像转卡通",
      "AI美图",
      "头像制作",
    ],
    seoDescription:
      "一键卡通化，让你瞬间穿越到二次元世界，生成高质量的动漫风格头像和全身像。",
    model: "to-anime-filter-2",
    source: "豆包",
    icon: "https://img.daisyui.com/images/profile/demo/yellingcat@192.webp",
    barImg: "",
    rate: sql`'0.0'::numeric`,
    useCount: 4500,
    points: 1,
    status: AppStatus.Enabled,
    tags: ["卡通", "二次元", "动漫", "滤镜", "头像"], 
  },
  {
    routeId: "10018",
    name: "AI排版助手",
    category: AppCategories.CreativeDesign,
    keywords: ["排版", "布局", "设计", "海报"],
    description: "输入图片和文字，AI自动生成多种创意且专业的布局排版设计",
    seoKeywords: [
      "设计排版",
      "创意布局",
      "AI设计",
      "海报制作",
      "平面设计",
    ],
    seoDescription:
      "AI排版助手，解决你的设计布局难题。为你的内容提供多种专业、美观的排版方案。",
    model: "layout-designer-1",
    source: "豆包",
    icon: "https://img.daisyui.com/images/profile/demo/yellingcat@192.webp",
    barImg: "",
    rate: sql`'0.0'::numeric`,
    useCount: 1600,
    points: 1,
    status: AppStatus.Enabled,
    tags: ["排版", "布局", "设计", "平面", "海报"], 
  },
  {
    routeId: "10019",
    name: "产品概念渲染",
    category: AppCategories.CreativeDesign,
    keywords: ["产品设计", "渲染", "3D", "概念图"],
    description: "上传产品草图，AI为其生成逼真的材质和场景渲染效果图",
    seoKeywords: [
      "产品渲染",
      "概念设计",
      "3D可视化",
      "AI建模",
      "工业设计",
    ],
    seoDescription:
      "产品概念渲染，快速将你的产品创意转化为高精度的商业级渲染图，加速产品演示。",
    model: "product-render-4",
    source: "豆包",
    icon: "https://img.daisyui.com/images/profile/demo/yellingcat@192.webp",
    barImg: "",
    rate: sql`'0.0'::numeric`,
    useCount: 500,
    points: 1,
    status: AppStatus.Enabled,
    tags: ["产品", "渲染", "3D", "概念", "工业设计"], 
  },
  {
    routeId: "10020",
    name: "像素艺术转换",
    category: AppCategories.CreativeDesign,
    keywords: ["像素", "复古", "游戏", "艺术"],
    description: "将任意图片转换为各种风格的复古像素艺术（Pixel Art）",
    seoKeywords: [
      "像素艺术",
      "Pixel Art",
      "复古游戏",
      "AI转换",
      "创意设计",
    ],
    seoDescription:
      "像素艺术转换，重温经典游戏的魅力。一键将照片变成精美的复古像素画作。",
    model: "pixel-art-1",
    source: "豆包",
    icon: "https://img.daisyui.com/images/profile/demo/yellingcat@192.webp",
    barImg: "",
    rate: sql`'0.0'::numeric`,
    useCount: 1400,
    points: 1,
    status: AppStatus.Enabled,
    tags: ["像素", "PixelArt", "复古", "游戏", "艺术"], 
  },
];
